Repository ShyPolarBear/Server, pull requests merged in 2023-09, with the labels that each got.

#62 Feature/전체 피드 조회
  src/main/java/com/shy_polarbear/server/domain/comment/model/Comment.java
  src/main/java/com/shy_polarbear/server/domain/comment/model/CommentLike.java
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentRepository.java
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/comment/service/CommentService.java
  src/main/java/com/shy_polarbear/server/domain/feed/controller/FeedController.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/FeedCardResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/FeedLike.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedLikeRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/feed/service/FeedService.java
  src/main/java/com/shy_polarbear/server/domain/feed/service/FeedSort.java
  src/main/java/com/shy_polarbear/server/global/common/constants/BusinessLogicConstants.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
Labels: 🌿 feature

#63 fix: 퀴즈 제출 시간초과 로직 추가
  src/main/java/com/shy_polarbear/server/domain/point/service/PointService.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/request/MultipleChoiceQuizScoreRequest.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/request/OXQuizScoreRequest.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/response/MultipleChoiceQuizScoreResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/response/OXQuizScoreResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/service/QuizService.java
  src/main/java/com/shy_polarbear/server/global/exception/ExceptionStatus.java
Labels: 🚑 fix

#65 fix: 커스텀커서로 변경
  build.gradle
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedLikeRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedLikeRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedLikeRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/feed/service/FeedService.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
Labels: 🚑 fix

#66 fix: 복습 퀴즈 조회 랜덤 로직으로 변경
  src/main/java/com/shy_polarbear/server/domain/quiz/controller/QuizController.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/QuizRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/QuizRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/quiz/service/QuizService.java
  src/main/java/com/shy_polarbear/server/global/common/util/query/CustomOrderSpecifierUtils.java
Labels: 🚑 fix

#68 Fix/ 피드 작성 시 피드이미지 없는 경우 해결
  src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
  src/main/java/com/shy_polarbear/server/domain/images/service/S3FileService.java
Labels: 🐛 bug

#69 refactor: ControllerAdvice 런타임 에러 스택 출력
  src/main/java/com/shy_polarbear/server/global/exception/ControllerAdvice.java
Labels: 🛠 refactor

#70 refactor: 이미지 업로드 api 인증 제외
  spy.log
  src/main/java/com/shy_polarbear/server/global/auth/security/SecurityConfig.java
  src/main/java/com/shy_polarbear/server/global/common/constants/GlobalConstants.java
Labels: 🛠 refactor

#67 test: 퀴즈 테스트
  build.gradle
  src/main/java/com/shy_polarbear/server/domain/point/model/Point.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/MultipleChoice.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/Quiz.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/QuizRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/QuizRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/quiz/service/QuizService.java
  src/main/java/com/shy_polarbear/server/global/common/constants/ProfileConstants.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/LoginUserInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/QuizInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/util/profiles/CustomProfileUtils.java
  src/test/java/com/shy_polarbear/server/config/TestJpaConfig.java
  src/test/java/com/shy_polarbear/server/domain/quiz/model/OXQuizTest.java
  src/test/java/com/shy_polarbear/server/domain/quiz/repository/QuizRepositoryTest.java
  src/test/java/com/shy_polarbear/server/domain/quiz/service/QuizServiceTest.java
  src/test/java/com/shy_polarbear/server/domain/quiz/template/QuizTemplate.java
  src/test/java/com/shy_polarbear/server/domain/user/template/UserTemplate.java
Labels: 🌿 feature

#72 [WBS-81] 댓글, 대댓글 API 구현
  src/main/java/com/shy_polarbear/server/domain/comment/controller/CommentController.java
  src/main/java/com/shy_polarbear/server/domain/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/shy_polarbear/server/domain/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/shy_polarbear/server/domain/comment/dto/response/ChildCommentResponse.java
  src/main/java/com/shy_polarbear/server/domain/comment/dto/response/CommentCreateResponse.java
  src/main/java/com/shy_polarbear/server/domain/comment/dto/response/CommentDeleteResponse.java
  src/main/java/com/shy_polarbear/server/domain/comment/dto/response/CommentLikeResponse.java
  src/main/java/com/shy_polarbear/server/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/shy_polarbear/server/domain/comment/dto/response/CommentUpdateResponse.java
  src/main/java/com/shy_polarbear/server/domain/comment/exception/CommentException.java
  src/main/java/com/shy_polarbear/server/domain/comment/model/Comment.java
  src/main/java/com/shy_polarbear/server/domain/comment/model/CommentLike.java
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentLikeRepository.java
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/comment/service/CommentService.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/FeedCardResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/service/FeedService.java
  src/main/java/com/shy_polarbear/server/domain/user/model/User.java
  src/main/java/com/shy_polarbear/server/global/common/constants/BusinessLogicConstants.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/CommentInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/LoginUserInitializer.java
  src/main/java/com/shy_polarbear/server/global/exception/ExceptionStatus.java
  src/test/java/com/shy_polarbear/server/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/shy_polarbear/server/domain/comment/service/CommentServiceTest.java
  src/test/java/com/shy_polarbear/server/domain/comment/template/CommentTemplate.java
  src/test/java/com/shy_polarbear/server/domain/feed/template/FeedTemplate.java
  src/test/java/com/shy_polarbear/server/domain/user/template/UserTemplate.java
Labels: 🌿 feature

#74 fix: 피드 이미지 수정 시 버그 해결
  src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UpdateUserInfoResponse.java
  src/main/java/com/shy_polarbear/server/global/common/dto/NoCountPageResponse.java
  src/main/java/com/shy_polarbear/server/global/common/dto/PageResponse.java
Labels: 🐛 bug

#75 fix: 스프링 컨텍스트에 있는 객체 사용하게 변경
  spy.log
  src/main/java/com/shy_polarbear/server/domain/feed/controller/FeedController.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/FeedCardResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/FeedLike.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedLikeRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/service/FeedService.java
  src/main/java/com/shy_polarbear/server/domain/user/controller/AuthController.java
  src/main/java/com/shy_polarbear/server/domain/user/controller/UserController.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserCommentFeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserFeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/service/AuthService.java
  src/main/java/com/shy_polarbear/server/domain/user/service/UserService.java
  src/main/java/com/shy_polarbear/server/global/auth/jwt/JwtProvider.java
  src/main/java/com/shy_polarbear/server/global/auth/jwt/RefreshTokenRepository.java
  src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
  src/test/java/com/shy_polarbear/server/domain/user/service/UserServiceTest.java
Labels: 🐛 bug

#78 fix: 내가 댓글을 작성한 피드 (+리팩토링)
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/user/controller/UserController.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserCommentFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserCommentFeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserFeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/service/UserService.java
  src/main/java/com/shy_polarbear/server/global/common/constants/BusinessLogicConstants.java
Labels: 🐛 bug, 🛠 refactor

#79 fix: 코멘트 조회 쿼리문 조인 오류
  src/main/java/com/shy_polarbear/server/domain/comment/repository/CommentRepositoryImpl.java
Labels: 🚑 fix
