Repository ShyPolarBear/Server, pull requests merged in 2023-08, with the labels that each got.

#42 fix: PostConstruct 컴포넌트 순서 문제
  src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/LoginUserInitializer.java
Labels: enhancement

#43 feat: 초기 셋업
  .gitignore
  src/main/java/com/shy_polarbear/server/domain/HealthCheckController.java
  src/main/java/com/shy_polarbear/server/global/auth/security/SecurityConfig.java
  src/main/java/com/shy_polarbear/server/global/common/constants/GlobalConstants.java
  src/main/java/com/shy_polarbear/server/global/common/dto/NoCountPageResponse.java
  src/main/java/com/shy_polarbear/server/global/common/dto/PageResponse.java
Labels: enhancement

#40 [WBS-79] 환경 피드 작성, 전체 피드 조회(무한 스크롤), 피드 상세 조회, 피드 수정, 피드 삭제
  src/main/java/com/shy_polarbear/server/domain/feed/controller/FeedController.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/CreateFeedRequest.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/CreateFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/DeleteFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/FeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/FeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/LikeFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/ReportFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/UpdateFeedRequest.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/UpdateFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/service/FeedService.java
  src/main/java/com/shy_polarbear/server/global/common/dto/ApiResponse.java
Labels: 🌿 feature

#50 Feature/피드 작성, 수정, 삭제, 좋아요, 상세조회 api
  src/main/java/com/shy_polarbear/server/ServerApplication.java
  src/main/java/com/shy_polarbear/server/domain/feed/controller/FeedController.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/CreateFeedRequest.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/CreateFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/DeleteFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/FeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/FeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/LikeFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/ReportFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/UpdateFeedRequest.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/UpdateFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/request/CreateFeedRequest.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/request/UpdateFeedRequest.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/CreateFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/DeleteFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/FeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/LikeFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/UpdateFeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/feed/exception/FeedException.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/FeedImage.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/FeedLike.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedLikeRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/repository/FeedRepository.java
  src/main/java/com/shy_polarbear/server/domain/feed/service/FeedService.java
  src/main/java/com/shy_polarbear/server/domain/images/service/ImageService.java
  src/main/java/com/shy_polarbear/server/domain/user/controller/AuthController.java
  src/main/java/com/shy_polarbear/server/domain/user/controller/UserController.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/auth/request/JoinRequest.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/auth/request/LoginRequest.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/auth/request/ReissueRequest.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/auth/request/SocialLoginRequest.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/request/UpdateUserInfoRequest.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserCommentFeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserFeedsResponse.java
  src/main/java/com/shy_polarbear/server/global/common/dto/ApiResponse.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/model/BaseEntity.java
  src/main/java/com/shy_polarbear/server/global/exception/ExceptionStatus.java
Labels: 🌿 feature

#51 [WBS-78] 퀴즈 API
  build.gradle
  src/main/java/com/shy_polarbear/server/domain/point/model/Point.java
  src/main/java/com/shy_polarbear/server/domain/point/model/PointType.java
  src/main/java/com/shy_polarbear/server/domain/point/repository/PointRepository.java
  src/main/java/com/shy_polarbear/server/domain/point/service/PointService.java
  src/main/java/com/shy_polarbear/server/domain/quiz/controller/QuizController.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/MultipleChoiceQuizScoreRequest.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/MultipleChoiceQuizScoreResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/MultipleChoiceResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/OXQuizScoreRequest.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/OXQuizScoreResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/QuizCardResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/QuizType.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/WhetherDailyQuizSolvedResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/exception/QuizException.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/MultipleChoice.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/MultipleChoiceQuiz.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/OXChoice.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/OXQuiz.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/Quiz.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/UserQuiz.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/MultipleChoiceQuizRepository.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/MultipleChoiceRepository.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/OXQuizRepository.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/QuizRepository.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/QuizRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/QuizRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/UserQuizRepository.java
  src/main/java/com/shy_polarbear/server/domain/quiz/service/QuizService.java
  src/main/java/com/shy_polarbear/server/domain/ranking/model/Ranking.java
  src/main/java/com/shy_polarbear/server/domain/user/model/User.java
  src/main/java/com/shy_polarbear/server/domain/user/service/UserService.java
  src/main/java/com/shy_polarbear/server/global/common/config/QuerydslConfig.java
  src/main/java/com/shy_polarbear/server/global/common/constants/BusinessLogicConstants.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/QuizInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/util/CustomSliceExecutionUtils.java
  src/main/java/com/shy_polarbear/server/global/common/util/EnumModel.java
  src/main/java/com/shy_polarbear/server/global/common/util/EnumValue.java
  src/main/java/com/shy_polarbear/server/global/exception/ControllerAdvice.java
  src/main/java/com/shy_polarbear/server/global/exception/ExceptionStatus.java
Labels: 🌿 feature

#55 fix: 프로필이미지 nullable로 변경
  src/main/java/com/shy_polarbear/server/domain/feed/dto/response/FeedResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/auth/request/JoinRequest.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/request/UpdateUserInfoRequest.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UpdateUserInfoResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserCommentFeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserFeedsResponse.java
  src/main/java/com/shy_polarbear/server/domain/user/dto/user/response/UserInfoResponse.java
Labels: 🐛 bug, 🛠 refactor

#56 퀴즈 리팩토링
  .gitignore
  src/main/java/com/shy_polarbear/server/domain/point/service/PointService.java
  src/main/java/com/shy_polarbear/server/domain/quiz/controller/QuizController.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/request/MultipleChoiceQuizScoreRequest.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/request/OXQuizScoreRequest.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/response/MultipleChoiceQuizScoreResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/response/MultipleChoiceResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/response/OXQuizScoreResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/response/QuizCardResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/response/WhetherDailyQuizSolvedResponse.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/MultipleChoice.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/MultipleChoiceQuiz.java
  src/main/java/com/shy_polarbear/server/domain/quiz/model/UserQuiz.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/UserQuizRepository.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/UserQuizRepositoryCustom.java
  src/main/java/com/shy_polarbear/server/domain/quiz/repository/UserQuizRepositoryImpl.java
  src/main/java/com/shy_polarbear/server/domain/quiz/service/QuizService.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/QuizInitializer.java
Labels: 🛠 refactor

#57 테스트코드 작성, 리팩토링
  src/main/java/com/shy_polarbear/server/domain/feed/controller/FeedController.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/request/CreateFeedRequest.java
  src/main/java/com/shy_polarbear/server/domain/feed/dto/request/UpdateFeedRequest.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
  src/main/java/com/shy_polarbear/server/domain/feed/model/FeedImage.java
  src/main/java/com/shy_polarbear/server/domain/feed/service/FeedService.java
  src/main/java/com/shy_polarbear/server/domain/point/model/Point.java
  src/main/java/com/shy_polarbear/server/domain/user/controller/AuthController.java
  src/main/java/com/shy_polarbear/server/domain/user/controller/UserController.java
  src/main/java/com/shy_polarbear/server/domain/user/infra/ProviderType.java
  src/main/java/com/shy_polarbear/server/domain/user/model/ProviderType.java
  src/main/java/com/shy_polarbear/server/domain/user/model/User.java
  src/main/java/com/shy_polarbear/server/domain/user/repository/UserRepository.java
  src/main/java/com/shy_polarbear/server/domain/user/service/AuthService.java
  src/main/java/com/shy_polarbear/server/domain/user/service/UserService.java
  src/main/java/com/shy_polarbear/server/global/common/constants/BusinessLogicConstants.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/LoginUserInitializer.java
  src/main/java/com/shy_polarbear/server/global/common/dummy/QuizInitializer.java
  src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
  src/test/java/com/shy_polarbear/server/domain/point/model/PointTest.java
  src/test/java/com/shy_polarbear/server/domain/user/model/UserTest.java
  src/test/java/com/shy_polarbear/server/domain/user/service/UserServiceTest.java
  src/test/java/com/shy_polarbear/server/global/auth/jwt/JwtProviderTest.java
Labels: 🐛 bug, 🛠 refactor, 💦 stuck

#58 fix: 퀴즈 Request DTO Json parse error
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/request/MultipleChoiceQuizScoreRequest.java
  src/main/java/com/shy_polarbear/server/domain/quiz/dto/request/OXQuizScoreRequest.java
Labels: 🚑 fix
